const { ACTION_TYPES, PET_STATES } = require('../shared/config');

class ActionEngine {
  constructor(store, githubClient, petWindow) {
    this.store = store;
    this.githubClient = githubClient;
    this.petWindow = petWindow;
    this.discordBot = null;
    this.suggestions = new Map();
    this.history = [];
  }

  setDiscordBot(bot) {
    this.discordBot = bot;
  }

  setPetWindow(petWindow) {
    this.petWindow = petWindow;
  }

  async propose(suggestion) {
    this.suggestions.set(suggestion.id, suggestion);

    // Notify desktop pet
    this._sendToPet('new-suggestion', suggestion);
    this._setPetState(PET_STATES.EXCITED);

    // Forward to Discord if enabled
    if (this.discordBot) {
      try {
        const messageId = await this.discordBot.sendSuggestion(suggestion);
        suggestion.discordMessageId = messageId;
      } catch (err) {
        console.error('Failed to send suggestion to Discord:', err.message);
      }
    }

    return suggestion;
  }

  async approve(suggestionId) {
    const suggestion = this.suggestions.get(suggestionId);
    if (!suggestion || suggestion.status !== 'pending') return null;

    suggestion.status = 'approved';
    this._setPetState(PET_STATES.HAPPY);

    try {
      const result = await this._execute(suggestion);
      suggestion.status = 'executed';
      this.history.push({ ...suggestion, executedAt: new Date().toISOString() });
      this.suggestions.delete(suggestionId);

      this._sendToPet('suggestion-executed', { id: suggestionId, result });

      if (this.discordBot && suggestion.discordMessageId) {
        await this.discordBot.updateSuggestionStatus(suggestion.discordMessageId, 'approved', result);
      }

      return result;
    } catch (err) {
      suggestion.status = 'pending';
      this._setPetState(PET_STATES.SAD);
      console.error('Action execution failed:', err.message);
      throw err;
    }
  }

  async dismiss(suggestionId) {
    const suggestion = this.suggestions.get(suggestionId);
    if (!suggestion) return;

    suggestion.status = 'dismissed';
    this._setPetState(PET_STATES.SAD);
    this.history.push({ ...suggestion, dismissedAt: new Date().toISOString() });
    this.suggestions.delete(suggestionId);

    this._sendToPet('suggestion-dismissed', { id: suggestionId });

    if (this.discordBot && suggestion.discordMessageId) {
      await this.discordBot.updateSuggestionStatus(suggestion.discordMessageId, 'dismissed');
    }
  }

  async _execute(suggestion) {
    switch (suggestion.type) {
      case ACTION_TYPES.CREATE_ISSUE:
        return this._executeCreateIssue(suggestion);
      case ACTION_TYPES.UPDATE_BACKLOG:
        return this._executeUpdateBacklog(suggestion);
      case ACTION_TYPES.NOTIFY:
        return { notified: true };
      case ACTION_TYPES.OPEN_PROJECT:
        return this._executeOpenProject(suggestion);
      default:
        throw new Error(`Unknown action type: ${suggestion.type}`);
    }
  }

  async _executeCreateIssue(suggestion) {
    const repo = suggestion.payload?.githubRepo;
    if (!repo) throw new Error('No GitHub repo associated with this project');

    const body = `## Suggestion from Tamugatchi\n\n${suggestion.description}\n\n---\n*Auto-generated by Tamugatchi desktop pet*`;
    return this.githubClient.createIssue(repo, suggestion.title, body);
  }

  async _executeUpdateBacklog(suggestion) {
    const fs = require('fs');
    const path = require('path');
    const projects = this.store.get('trackedProjects', []);
    const project = projects.find(p => p.name === suggestion.projectName);
    if (!project) throw new Error(`Project not found: ${suggestion.projectName}`);

    const backlogPath = path.join(project.path, 'BACKLOG.md');
    let content = '';

    if (fs.existsSync(backlogPath)) {
      content = fs.readFileSync(backlogPath, 'utf8');
    } else {
      content = `# ${project.name} - Backlog\n\n`;
    }

    content += `\n- ${suggestion.title}: ${suggestion.description}\n`;
    fs.writeFileSync(backlogPath, content, 'utf8');

    return { file: backlogPath, added: suggestion.title };
  }

  _executeOpenProject(suggestion) {
    const { shell } = require('electron');
    const projects = this.store.get('trackedProjects', []);
    const project = projects.find(p => p.name === suggestion.projectName);

    if (project?.payload?.githubRepo) {
      shell.openExternal(`https://github.com/${project.payload.githubRepo}`);
    } else if (project) {
      shell.openPath(project.path);
    }

    return { opened: true };
  }

  getPendingSuggestions() {
    return Array.from(this.suggestions.values())
      .filter(s => s.status === 'pending');
  }

  getHistory() {
    return this.history;
  }

  getTodayStats() {
    const today = new Date().toISOString().slice(0, 10);
    const todayHistory = this.history.filter(h =>
      h.executedAt?.startsWith(today) || h.dismissedAt?.startsWith(today)
    );

    return {
      suggested: todayHistory.length + this.suggestions.size,
      approved: todayHistory.filter(h => h.status === 'executed').length,
      dismissed: todayHistory.filter(h => h.status === 'dismissed').length,
      pending: this.suggestions.size
    };
  }

  _sendToPet(channel, data) {
    if (this.petWindow && !this.petWindow.isDestroyed()) {
      this.petWindow.webContents.send(channel, data);
    }
  }

  _setPetState(state) {
    this.store.set('currentPetState', state);
    this._sendToPet('pet-state-change', state);

    // Reset to idle after 5 seconds for transient states
    if (state === PET_STATES.HAPPY || state === PET_STATES.SAD) {
      setTimeout(() => {
        this._setPetState(PET_STATES.IDLE);
      }, 5000);
    }
  }
}

module.exports = { ActionEngine };
